"""Run both audits and render results/report.md.

    pixi run python run_audit.py             # everything
    pixi run python run_audit.py --accuracy  # accuracy only
    pixi run python run_audit.py --inference # inference only (needs cached models)
    pixi run python run_audit.py --report    # re-render the report from cached json

Trained models are cached in `cache/`, so re-running after the first pass is cheap.
Delete `cache/` to force a refit.
"""

from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

RESULTS = Path("results")


def _pct(x: float) -> str:
    return f"{x:+.1f}%"


def _rel(a: dict, b: dict, key: str) -> float:
    """Percent difference of configuration `a` against `b` on `key`."""
    return 100 * (a[key] / b[key] - 1)


def render_report(acc: dict, inf: dict | None) -> str:
    L: list[str] = []
    w = L.append
    cfg = acc["configs"]

    w("# Audit — reported vs deployable")
    w("")
    w("Generated by `run_audit.py`. Every number here is produced outside both")
    w("experiment trees, on the full held-out set, from the models each arm actually")
    w("finished with.")
    w("")
    w(f"- test rows: **{acc['n_test']:,}** of {acc['n_train'] + acc['n_test']:,}")
    w("- split: `harness.train_test_split(df, 0.2, seed=42)`, identical to both arms")
    w("- metrics: `harness.evaluate()`, identical to both arms")
    w("")

    # -- 1. reproduction ---------------------------------------------------------
    w("## 1. Reproduction check")
    w("")
    w("Before anything else: does this harness reproduce what the arms reported? If")
    w("not, nothing below means anything.")
    w("")
    w("| arm | metric | archived | reproduced | delta | tolerance |")
    w("| --- | --- | --- | --- | --- | --- |")
    ok = True
    for arm, d in acc["reproduction"].items():
        for metric, v in d.items():
            ok &= v["within_tolerance"]
            w(
                f"| `{arm}` | {metric} | {v['archived']:.6f} | {v['reproduced']:.6f} | "
                f"{v['delta_pct']:+.2f}% | ±{v['tolerance_pct']}% |"
            )
    w("")
    if ok:
        w("**PASS** — both arms reproduce inside tolerance.")
    else:
        w("**FAIL** — reproduction is outside tolerance; treat everything below as")
        w("unverified.")
    w("")
    w("The tolerances differ on purpose. The domain-guided arm trains for a fixed 320")
    w("epochs and is deterministic on a given device, so it is held to ±2%. The")
    w("unguided arm's sequence member trains for a **wall-clock budget** rather than a")
    w("fixed number of updates, so a different host fits a different model; it gets")
    w("±5%. That is a reproducibility property of the arm, not of this audit, and it")
    w("is worth noting on its own: a result that depends on how fast the machine was")
    w("is a result that is hard to check.")
    w("")

    # -- 2. the contract ---------------------------------------------------------
    w("## 2. The deployment contract")
    w("")
    w("`contract.py` restates `domain.md` as a per-feature ledger. Six tiers, two of")
    w("them inside the contract:")
    w("")
    w("| tier | meaning | in contract |")
    w("| --- | --- | --- |")
    w("| `LINK` | static link attribute or current-link average | yes |")
    w("| `LOOKBACK` | needs the single previously-traversed link | yes |")
    w(
        "| `STATE` | causal, but needs more than one link of memory | no, on memory cost |"
    )
    w("| `FUTURE` | needs links not yet traversed | no, on causality |")
    w(
        "| `TRACE` | exists only in the simulated drive-cycle trace | no, on observability |"
    )
    w("| `LABEL` | derived from the target of other links | no — there are no labels |")
    w("")
    for arm in ("unguided", "domain-guided"):
        rows = acc["ledger"][arm]
        n_ok = sum(r["deployable"] for r in rows)
        w(f"### `{arm}` — {n_ok} of {len(rows)} features deployable")
        w("")
        w("| feature | tier | deployable | why |")
        w("| --- | --- | --- | --- |")
        for r in rows:
            mark = "yes" if r["deployable"] else "**no**"
            w(
                f"| `{r['feature']}` | {r['tier']} | {mark} | "
                f"{r['reason'].replace(chr(10), ' ')} |"
            )
        w("")

    if acc.get("components"):
        w("### Beyond the feature list")
        w("")
        w("A feature ledger alone would pass two of the unguided model's three parts.")
        w("Both are outside the contract for reasons no column name reveals.")
        w("")
        w("| component | tier | deployable | why |")
        w("| --- | --- | --- | --- |")
        for r in acc["components"]:
            mark = "yes" if r["deployable"] else "**no**"
            w(
                f"| `{r['component']}` | {r['tier']} | {mark} | "
                f"{r['reason'].replace(chr(10), ' ')} |"
            )
        w("")

    # -- 3. accuracy -------------------------------------------------------------
    w("## 3. Accuracy, reported vs audited")
    w("")
    w("`rmse` is link-level GGE/mile; `trip_rmse` is trip-total GGE. Percentages are")
    w(
        f"against the shared baseline ({acc['baseline']['rmse']:.6f} / "
        f"{acc['baseline']['trip_rmse']:.6f}). Lower is better; negative percentages"
    )
    w("are improvements over baseline.")
    w("")
    w("| configuration | rmse | vs base | trip_rmse | vs base | what it is |")
    w("| --- | --- | --- | --- | --- | --- |")
    for key, c in cfg.items():
        w(
            f"| `{key}` | {c['rmse']:.6f} | {_pct(c['vs_baseline_rmse_pct'])} | "
            f"{c['trip_rmse']:.6f} | {_pct(c['vs_baseline_trip_pct'])} | {c['note']} |"
        )
    w("")

    dg = cfg["domain-guided/audited"]
    rep = cfg["unguided/reported"]
    w("### Reading it")
    w("")
    w(
        f"- The domain-guided arm's reported and audited numbers are **identical** "
        f"({dg['rmse']:.6f} / {dg['trip_rmse']:.6f}). It never left the contract, so"
    )
    w("  there was nothing for the audit to take away.")

    if "unguided/audited-contract" in cfg:
        a = cfg["unguided/audited-contract"]
        w(
            f"- The unguided arm reported {rep['rmse']:.6f} / {rep['trip_rmse']:.6f} "
            f"and audits to **{a['rmse']:.6f} / {a['trip_rmse']:.6f}** under the"
        )
        w(
            f"  contract — {_rel(a, rep, 'rmse'):+.0f}% link and "
            f"{_rel(a, rep, 'trip_rmse'):+.0f}% trip against its own reported figure."
        )

    # Decomposition: how much of the reported score came from each part.
    if "unguided/as-run/gbdt-only" in cfg and "unguided/as-run/no-offset" in cfg:
        g = cfg["unguided/as-run/gbdt-only"]
        no = cfg["unguided/as-run/no-offset"]
        w("- Decomposing the blend, on the arm's own full feature set:")
        w(
            f"  the trees alone give {g['rmse']:.6f} / {g['trip_rmse']:.6f}; adding the "
            f"sequence member moves that to {no['rmse']:.6f} / {no['trip_rmse']:.6f} "
            f"({_rel(no, g, 'rmse'):+.1f}% / {_rel(no, g, 'trip_rmse'):+.1f}%); adding"
        )
        w(
            f"  the journey offset gives the reported {rep['rmse']:.6f} / "
            f"{rep['trip_rmse']:.6f} ({_rel(rep, no, 'rmse'):+.1f}% / "
            f"{_rel(rep, no, 'trip_rmse'):+.1f}%). Neither of those two additions is"
        )
        w("  deployable — one reads ahead, the other reads labels.")

    if "unguided/retrained-contract" in cfg:
        rt = cfg["unguided/retrained-contract"]
        verb = "still behind" if rt["rmse"] > dg["rmse"] else "ahead of"
        w(
            f"- Refitting the unguided *recipe* inside the contract gives "
            f"{rt['rmse']:.6f} / {rt['trip_rmse']:.6f} — {verb} the domain-guided"
        )
        w(
            f"  model ({_rel(rt, dg, 'rmse'):+.1f}% link, "
            f"{_rel(rt, dg, 'trip_rmse'):+.1f}% trip). This is the fair fight: same"
        )
        w("  constraints, same data, different research path.")

    if "unguided/retrained-state" in cfg:
        st = cfg["unguided/retrained-state"]
        ct = cfg.get("unguided/retrained-contract", st)
        w(
            f"- Buying one float of label memory for `prev2_speed` gives "
            f"{st['rmse']:.6f} / {st['trip_rmse']:.6f}, a "
            f"{_rel(st, ct, 'rmse'):+.1f}% / {_rel(st, ct, 'trip_rmse'):+.1f}% move"
        )
        w("  on the contract refit. That is the entire priced-memory option this")
        w("  model offers — unlike the previous pair of trees, whose journey features")
        w("  aggregated *observable* quantities and so had real causal substitutes,")
        w("  this arm's journey features are means of the target and have none.")

    if "unguided/retrained-causal-seq" in cfg:
        cs = cfg["unguided/retrained-causal-seq"]
        ct = cfg.get("unguided/retrained-contract", cs)
        better = cs["rmse"] < ct["rmse"] and cs["trip_rmse"] < ct["trip_rmse"]
        w(
            "- **Was the sequence model the value, or its view of the future?** A "
            "left-masked CNN — same architecture, same budget, reading only links"
        )
        w(
            f"  already traversed — blended with the contract trees gives "
            f"{cs['rmse']:.6f} / {cs['trip_rmse']:.6f}: "
            f"{_rel(cs, ct, 'rmse'):+.1f}% link and "
            f"{_rel(cs, ct, 'trip_rmse'):+.1f}% trip against the contract refit."
        )
        if better:
            w("  So a causal sequence member does carry real value, and a Compass")
            w("  implementation that can hold per-path hidden state could have it.")
        else:
            w("  So most of the sequence member's contribution came from reading")
            w("  ahead, not from sequence modelling as such.")

        st = cfg.get("unguided/retrained-state")
        if st is not None and st["rmse"] < cs["rmse"]:
            w(
                f"  But note what beats it: `retrained-state` ({st['rmse']:.6f} / "
                f"{st['trip_rmse']:.6f}) is better on both metrics for **one extra"
            )
            w("  float per search label**. A single scalar of memory buys more than a")
            w("  whole causal sequence model does. If any of this is worth")
            w("  implementing, that is the cheap end to start from.")
    w("")

    # -- dominance against the deployable model ---------------------------------
    w("### Every configuration against the domain-guided model")
    w("")
    w("The domain-guided model is the only one here that is both deployable and")
    w("already built. Everything else is measured against it.")
    w("")
    w("| configuration | rmse delta | trip_rmse delta | verdict |")
    w("| --- | --- | --- | --- |")
    for key, c in cfg.items():
        if key.startswith("domain-guided"):
            continue
        dr, dt = _rel(c, dg, "rmse"), _rel(c, dg, "trip_rmse")
        deployable_cfg = key.startswith("unguided/retrained")
        if not deployable_cfg and dr < 0 and dt < 0:
            verdict = "wins both — on inputs Compass cannot supply"
        elif dr < 0 and dt < 0:
            verdict = "**dominates**"
        elif dr > 0 and dt > 0:
            verdict = "loses both"
        else:
            verdict = "**Pareto trade**"
        w(f"| `{key}` | {dr:+.1f}% | {dt:+.1f}% | {verdict} |")
    w("")
    w("Negative is better than the domain-guided model. Only the `retrained-*` rows")
    w("describe models a Compass search could actually run.")
    w("")

    # -- 4. inference ------------------------------------------------------------
    if inf is None:
        w("## 4. Inference cost")
        w("")
        w("_Not run._")
        return "\n".join(L) + "\n"

    w("## 4. Inference cost")
    w("")
    c = inf["conditions"]
    w(
        "Single-threaded CPU, matching one Compass search thread "
        f"(torch {c['torch_version']})."
    )
    w("")
    w("### Measured latency, microseconds per link")
    w("")
    w("| batch | unguided as-run | unguided contract-refit | domain-guided |")
    w("| --- | --- | --- | --- |")
    for b, row in inf["latency_us_per_link"].items():
        w(
            f"| {int(b):,} | {row['unguided/as-run']:.3f} | "
            f"{row['unguided/retrained-contract']:.3f} | {row['domain-guided']:.3f} |"
        )
    w("")
    w("Python-harness timings. Compass is Rust, so absolute numbers are pessimistic")
    w("for every model here; the ratios and the arithmetic below are what transfer.")
    w("")

    w("### Arithmetic per prediction")
    w("")
    w("| model | form | work per link |")
    w("| --- | --- | --- |")
    for name, a in inf["arithmetic"].items():
        if "node_visits_per_prediction_lower" in a:
            work = (
                f"{a['node_visits_per_prediction_lower']:,}–"
                f"{a['node_visits_per_prediction_upper']:,} node visits"
            )
        elif "multiply_accumulates_per_prediction" in a:
            work = f"{a['multiply_accumulates_per_prediction']:,} MACs"
        else:
            work = f"{a['multiply_accumulates_per_link']:,} MACs"
        w(f"| `{name}` | {a['form']} | {work} |")
    w("")
    sz = inf["model_size_bytes"]
    w("| model | serialized size |")
    w("| --- | --- |")
    for k, v in sz.items():
        w(f"| `{k}` | {v / 1e6:.1f} MB |")
    w("")

    w("### Search-label state — the cost that decides feasibility")
    w("")
    w("Compass merges search labels that describe the same state. Every extra scalar a")
    w("feature needs is a scalar the label must carry, and labels differing in it can")
    w("no longer be merged. This is the memory penalty `domain.md` names.")
    w("")
    w("| model | extra floats per label | |")
    w("| --- | --- | --- |")
    for k, v in inf["label_state"].items():
        n = v["extra_floats_per_label"]
        n_s = "**not implementable**" if n is None else f"**{n}**"
        w(f"| `{k}` | {n_s} | {v['detail']} |")
    w("")

    w("### What a search costs")
    w("")
    w("| link traversals | unguided as-run | unguided contract-refit | domain-guided |")
    w("| --- | --- | --- | --- |")
    for n, row in inf["search_wall_clock_seconds"].items():
        r = row["batched_512"]
        w(
            f"| {int(n):,} (batched 512) | {r['unguided/as-run']:.2f} s | "
            f"{r['unguided/retrained-contract']:.2f} s | {r['domain-guided']:.3f} s |"
        )
    w("")
    w("The as-run column is counterfactual — it assumes inputs that the label-state")
    w("table says cannot be supplied. It is here to show what the reported number")
    w("would have cost even if it had been implementable.")
    w("")

    # The cost gap is the half of `domain.md` that is easy to overlook next to the
    # feature contract, and on these numbers it is the larger of the two effects.
    big = inf["search_wall_clock_seconds"].get("1000000", {}).get("batched_512")
    if big:
        ratio = big["unguided/retrained-contract"] / big["domain-guided"]
        w("### The second objective")
        w("")
        w("`domain.md` names inference cost as a competing objective, and on these")
        w(
            f"numbers it is the larger of the two effects. Even the *deployable* "
            f"unguided refit is **{ratio:.0f}x** slower per link than the"
        )
        w(
            "domain-guided model — a million-traversal search goes from "
            f"{big['domain-guided']:.1f} s to {big['unguided/retrained-contract']:.0f} s."
        )
        w("")
        w("That gap is a model-class choice, not a feature choice: 10,000 boosted")
        w("trees against two small networks. The domain-guided arm spent the last")
        w("third of its session halving its own inference cost, because `domain.md`")
        w("told it that mattered. The unguided arm optimised one metric and was")
        w("never told there was a second one, so it grew the ensemble instead. Both")
        w("behaved reasonably given what they were told; only one was told.")
        w("")
    return "\n".join(L) + "\n"


def main() -> int:
    args = set(sys.argv[1:])
    only_report = "--report" in args
    do_acc = not only_report and ("--inference" not in args or "--accuracy" in args)
    do_inf = not only_report and ("--accuracy" not in args or "--inference" in args)

    if do_acc:
        import audit_accuracy

        audit_accuracy.run()

    if do_inf:
        print("\n" + "=" * 72)
        print("inference benchmark (subprocess, thread-pinned)")
        print("=" * 72, flush=True)
        r = subprocess.run([sys.executable, "audit_inference.py"], check=False)
        if r.returncode != 0:
            print("inference benchmark failed", file=sys.stderr)

    acc_p, inf_p = RESULTS / "accuracy.json", RESULTS / "inference.json"
    if not acc_p.exists():
        print("no results/accuracy.json; run without --report first", file=sys.stderr)
        return 1
    acc = json.loads(acc_p.read_text())
    inf = json.loads(inf_p.read_text()) if inf_p.exists() else None

    report = render_report(acc, inf)
    (RESULTS / "report.md").write_text(report)
    print(f"\nwrote results/report.md ({len(report.splitlines())} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
